import type { Language, TrainingType } from './types/training';

export interface StageLines { opening: string; onClarify: string; onEmpathy: string; onSpecific: string; fallback: string; }
export interface CurriculumScenario { id: string; title: string; situation: string; characterName: string; characterRole: string; stages: StageLines[]; }
export interface Curriculum { id: string; version: string; type: TrainingType; title: string; description: string; learningObjectives: string[]; scenarios: CurriculumScenario[]; }

const makeStage = (opening:string,onClarify:string,onEmpathy:string,onSpecific:string,fallback:string):StageLines => ({opening,onClarify,onEmpathy,onSpecific,fallback});

const en: Record<TrainingType, Curriculum> = {
 feedback:{id:'feedback-manager-v1',version:'1.1',type:'feedback',title:'Constructive Feedback · Manager Essentials',description:'Practice turning labels and assumptions into observable behaviour and useful questions.',learningObjectives:['Describe observable behaviour','Separate facts from assumptions','Ask a clarifying question','Close with a concrete next step'],scenarios:[
  {id:'late-delivery',title:'Late delivery',situation:'A team member has submitted several tasks late and the delays are starting to affect the team.',characterName:'Alex',characterRole:'Your Team Member',stages:[
   makeStage('I know the task was late, but I have been dealing with several problems recently.','I have been overwhelmed with multiple projects recently.','Thank you for understanding. I did not know how to explain the situation.','The new client project has taken much more time than expected.','I am not sure I follow — could you tell me more about what you mean?'),
   makeStage('I did not want to bring it up earlier because I was not sure how you would react.','I was worried it would sound like an excuse.','That means a lot, thank you. It has been a hard few weeks.','I have had to support a teammate who was out sick, on top of my own work.','I hear you. What would help you understand this better?'),
   makeStage('Honestly, I did not realize how much this was affecting the team until now.','I underestimated how tight the deadline actually was.','I appreciate you not jumping to conclusions about me.','I can prioritize your deliverables first starting tomorrow.','Can you clarify what you would like me to focus on?'),
   makeStage('I want to fix this. What would a good outcome look like for you?','A clear plan would help both of us, I think.','I feel like we can actually solve this together now.','I will send you a revised timeline by end of day.','Let us figure out next steps together — what do you suggest?')]},
  {id:'quality-gap',title:'Quality gap',situation:'A capable team member has started submitting work that needs repeated corrections.',characterName:'Maya',characterRole:'Your Team Member',stages:[
   makeStage('I thought the work was good enough, so I was surprised by the feedback.','Which part of the deliverable created the biggest problem?','I appreciate you explaining it without making it personal.','The requirements changed twice while I was working on it.','Can you give me an example of what you mean?'),
   makeStage('I have been trying to move faster because the team is under pressure.','I may have rushed the review step.','That is helpful to hear. I was worried you had lost confidence in me.','I can add a review checkpoint before I submit the next version.','What would you like me to change first?'),
   makeStage('I can see now that speed was not the only goal.','Would you like me to check the requirements with you before I start?','That makes the expectation much clearer.','I will send a short checklist with the next draft.','Could we agree on what “ready” means before the next submission?'),
   makeStage('I think I know what I need to do differently now.','A specific quality checklist would help me repeat this consistently.','Thanks for giving me a way forward.','I will use the checklist on the next three submissions.','What is the most important thing you want me to remember?')]}] },
 conflict:{id:'conflict-conversation-v1',version:'1.1',type:'conflict',title:'Difficult Conflict · Manager Essentials',description:'Practice slowing down a tense conversation and replacing conclusions with questions.',learningObjectives:['Notice your first interpretation','Ask before attributing intent','Acknowledge impact','Agree on a next step'],scenarios:[{id:'meeting-friction',title:'Meeting friction',situation:'A colleague repeatedly interrupts you in meetings, and you are beginning to interpret it as disrespect.',characterName:'Jordan',characterRole:'Your Colleague',stages:[
  makeStage('I did not realize the interruptions were landing that way.','Can you tell me which moments felt most disruptive?','I can see why that would be frustrating.','I was worried we would run out of time and tried to keep the discussion moving.','I think we may be seeing the same meeting differently.'),
  makeStage('I can understand why you might think I was dismissing you.','Was there a specific meeting that made this especially difficult?','I appreciate you telling me directly.','I can write down my point and wait until you finish next time.','What would make the next meeting feel different for you?'),
  makeStage('I would rather fix the pattern than argue about who was right.','What would you notice if I handled this better?','That sounds like a fair way to approach it.','I will hold my comments until you finish your point.','What is one change we can both try?'),
  makeStage('That feels practical. I can work with that.','Should we check in after the next meeting?','Thanks for addressing it with me.','Let us review how it went after Friday.','I think we have a workable plan.')]}] },
 leadership:{id:'leadership-conversation-v1',version:'1.1',type:'leadership',title:'Leadership Conversations · Manager Essentials',description:'Practice moving from giving answers to creating ownership through specific questions.',learningObjectives:['Stay curious under pressure','Invite ownership','Clarify expectations','End with a shared commitment'],scenarios:[{id:'ownership-gap',title:'Ownership gap',situation:'A direct report keeps waiting for your instructions instead of taking ownership of routine decisions.',characterName:'Sam',characterRole:'Your Direct Report',stages:[
  makeStage('I usually wait because I do not want to make the wrong call.','Which decisions feel unclear to you?','I appreciate you explaining that. I do not want you to feel set up to fail.','I think I need clearer boundaries about what I can decide alone.','I am trying to understand what you expect from me.'),
  makeStage('I realize I may have asked for approval too often.','Which decisions would you trust me to make?','It helps to know you want me to grow into this.','I can own the weekly prioritization without checking every detail.','Could we define the decisions I should own?'),
  makeStage('That would give me more room to act.','What would success look like after a month?','I feel more confident knowing the boundary.','I will bring you exceptions instead of asking about routine choices.','I think I understand the new expectation.'),
  makeStage('I can take that on.','Can we review the first few decisions together?','Thanks for giving me room to practice.','I will make the next decision independently and explain my reasoning.','I am ready to try it.')]}] }
};

const id: Record<TrainingType,Curriculum> = {
 feedback:{...en.feedback,id:'feedback-manager-id-v1',title:'Umpan Balik Konstruktif · Dasar Manajer',description:'Latih cara mengubah label dan asumsi menjadi perilaku yang dapat diamati dan pertanyaan yang berguna.',learningObjectives:['Jelaskan perilaku yang dapat diamati','Pisahkan fakta dari asumsi','Ajukan pertanyaan klarifikasi','Tutup dengan langkah konkret'],scenarios:[
  {id:'late-delivery',title:'Tugas terlambat',situation:'Seorang anggota tim beberapa kali mengumpulkan tugas terlambat dan keterlambatan mulai berdampak pada tim.',characterName:'Alex',characterRole:'Anggota Tim Anda',stages:[
   makeStage('Saya tahu tugasnya terlambat, tetapi akhir-akhir ini saya menghadapi beberapa masalah.','Saya kewalahan dengan beberapa proyek sekaligus.','Terima kasih sudah memahami. Saya tidak tahu bagaimana menjelaskan situasinya.','Proyek klien baru ternyata membutuhkan jauh lebih banyak waktu dari perkiraan.','Saya kurang memahami maksud Anda — bisa ceritakan lebih lanjut?'),
   makeStage('Saya tidak ingin membicarakannya lebih awal karena tidak yakin bagaimana Anda akan bereaksi.','Saya khawatir ini terdengar seperti alasan.','Artinya besar bagi saya, terima kasih. Beberapa minggu terakhir memang berat.','Saya harus membantu rekan yang sedang sakit, selain pekerjaan saya sendiri.','Saya mengerti. Apa yang akan membantu Anda memahami situasi ini lebih baik?'),
   makeStage('Sejujurnya, saya baru sadar seberapa besar dampaknya pada tim.','Saya meremehkan betapa ketatnya tenggat waktunya.','Saya menghargai Anda tidak langsung berasumsi tentang saya.','Mulai besok saya bisa memprioritaskan pekerjaan yang menjadi tanggung jawab Anda.','Bisa diperjelas apa yang ingin Anda prioritaskan?'),
   makeStage('Saya ingin memperbaikinya. Menurut Anda, hasil yang baik itu seperti apa?','Rencana yang jelas akan membantu kita berdua.','Saya merasa kita benar-benar bisa menyelesaikan ini bersama.','Saya akan mengirim jadwal revisi hari ini sebelum jam kerja selesai.','Mari tentukan langkah berikutnya bersama — menurut Anda bagaimana?')]},
  {id:'quality-gap',title:'Kesenjangan kualitas',situation:'Seorang anggota tim yang sebenarnya mampu mulai mengirim pekerjaan yang membutuhkan banyak koreksi.',characterName:'Maya',characterRole:'Anggota Tim Anda',stages:[
   makeStage('Saya kira pekerjaannya sudah cukup baik, jadi saya terkejut dengan masukannya.','Bagian mana dari pekerjaan itu yang paling bermasalah?','Saya menghargai Anda menjelaskannya tanpa menjadikannya masalah pribadi.','Persyaratannya berubah dua kali saat saya mengerjakannya.','Bisa beri saya contoh yang Anda maksud?'),
   makeStage('Saya berusaha bekerja lebih cepat karena tim sedang berada di bawah tekanan.','Mungkin saya terlalu terburu-buru melewati tahap peninjauan.','Itu membantu untuk didengar. Saya khawatir Anda sudah kehilangan kepercayaan pada saya.','Saya bisa menambahkan titik pemeriksaan sebelum mengirim versi berikutnya.','Apa yang paling ingin Anda ubah terlebih dahulu?'),
   makeStage('Sekarang saya melihat bahwa kecepatan bukan satu-satunya tujuan.','Apakah Anda ingin saya memeriksa persyaratan dengan Anda sebelum mulai?','Itu membuat ekspektasinya jauh lebih jelas.','Saya akan mengirim checklist singkat bersama draf berikutnya.','Bisakah kita menyepakati seperti apa pekerjaan yang “siap” sebelum pengiriman berikutnya?'),
   makeStage('Saya rasa sekarang saya tahu apa yang perlu saya lakukan secara berbeda.','Checklist kualitas yang spesifik akan membantu saya konsisten.','Terima kasih sudah memberi saya jalan ke depan.','Saya akan menggunakan checklist pada tiga pengiriman berikutnya.','Apa satu hal terpenting yang ingin Anda saya ingat?')]}]},
 conflict:{...en.conflict,id:'conflict-conversation-id-v1',title:'Percakapan Konflik Sulit · Dasar Manajer',description:'Latih cara memperlambat percakapan tegang dan mengganti kesimpulan dengan pertanyaan.',learningObjectives:['Sadari interpretasi pertama Anda','Bertanya sebelum menilai niat','Akui dampak perilaku','Sepakati langkah berikutnya'],scenarios:[{id:'meeting-friction',title:'Gesekan dalam rapat',situation:'Seorang kolega berulang kali memotong pembicaraan Anda dalam rapat, dan Anda mulai menafsirkannya sebagai sikap tidak menghargai.',characterName:'Jordan',characterRole:'Kolega Anda',stages:[
  makeStage('Saya tidak sadar bahwa interupsi saya terasa seperti itu.','Bisa ceritakan momen mana yang paling mengganggu?','Saya bisa memahami mengapa itu membuat frustrasi.','Saya khawatir waktu kita habis dan mencoba menjaga diskusi tetap berjalan.','Saya rasa kita mungkin melihat rapat yang sama dari sudut berbeda.'),
  makeStage('Saya bisa memahami mengapa Anda mengira saya mengabaikan Anda.','Apakah ada rapat tertentu yang membuat hal ini terasa lebih sulit?','Saya menghargai Anda menyampaikannya secara langsung.','Saya bisa menuliskan poin saya dan menunggu sampai Anda selesai lain kali.','Apa yang akan membuat rapat berikutnya terasa berbeda bagi Anda?'),
  makeStage('Saya lebih ingin memperbaiki polanya daripada berdebat siapa yang benar.','Apa yang akan Anda lihat jika saya menangani ini dengan lebih baik?','Menurut saya itu cara yang adil untuk mendekatinya.','Saya akan menahan komentar sampai Anda selesai berbicara.','Apa satu perubahan yang bisa kita coba bersama?'),
  makeStage('Itu terasa praktis. Saya bisa menjalankannya.','Perlukah kita mengecek kembali setelah rapat berikutnya?','Terima kasih sudah membicarakannya dengan saya.','Mari kita tinjau bagaimana hasilnya setelah Jumat.','Saya rasa kita sudah punya rencana yang bisa dijalankan.')]}]},
 leadership:{...en.leadership,id:'leadership-conversation-id-v1',title:'Percakapan Kepemimpinan · Dasar Manajer',description:'Latih cara beralih dari memberi jawaban menjadi menciptakan rasa memiliki melalui pertanyaan spesifik.',learningObjectives:['Tetap ingin tahu di bawah tekanan','Mengundang rasa memiliki','Memperjelas ekspektasi','Mengakhiri dengan komitmen bersama'],scenarios:[{id:'ownership-gap',title:'Kesenjangan kepemilikan',situation:'Seorang bawahan langsung terus menunggu instruksi Anda alih-alih mengambil keputusan rutin secara mandiri.',characterName:'Sam',characterRole:'Bawahan Langsung Anda',stages:[
  makeStage('Saya biasanya menunggu karena tidak ingin membuat keputusan yang salah.','Keputusan apa yang terasa belum jelas bagi Anda?','Saya menghargai Anda menjelaskan itu. Saya tidak ingin Anda merasa dibiarkan gagal.','Saya rasa saya membutuhkan batasan yang lebih jelas tentang apa yang bisa saya putuskan sendiri.','Saya sedang mencoba memahami apa yang Anda harapkan dari saya.'),
  makeStage('Saya sadar mungkin terlalu sering meminta persetujuan.','Keputusan apa yang Anda percaya bisa saya buat sendiri?','Membantu mengetahui bahwa Anda ingin saya berkembang dalam hal ini.','Saya bisa mengambil keputusan prioritas mingguan tanpa memeriksa setiap detail.','Bisakah kita menentukan keputusan yang seharusnya saya miliki?'),
  makeStage('Itu akan memberi saya ruang lebih besar untuk bertindak.','Seperti apa keberhasilan setelah satu bulan?','Saya merasa lebih percaya diri karena batasannya jelas.','Saya akan membawa pengecualian kepada Anda, bukan meminta persetujuan untuk pilihan rutin.','Saya rasa saya memahami ekspektasi barunya.'),
  makeStage('Saya bisa mengambil tanggung jawab itu.','Bisakah kita meninjau beberapa keputusan pertama bersama?','Terima kasih sudah memberi saya ruang untuk berlatih.','Saya akan membuat keputusan berikutnya secara mandiri dan menjelaskan alasannya.','Saya siap mencobanya.')]}]}
};

const nl: Record<TrainingType,Curriculum> = {
 feedback:{...en.feedback,id:'feedback-manager-nl-v1',title:'Constructieve feedback · Voor managers',description:'Oefen om labels en aannames om te zetten in observeerbaar gedrag en bruikbare vragen.',learningObjectives:['Beschrijf observeerbaar gedrag','Scheid feiten van aannames','Stel een verhelderende vraag','Sluit af met een concrete vervolgstap'],scenarios:[
  {id:'late-delivery',title:'Te late oplevering',situation:'Een teamlid heeft meerdere taken te laat ingeleverd en de vertraging begint gevolgen te hebben voor het team.',characterName:'Alex',characterRole:'Jouw teamlid',stages:[
   makeStage('Ik weet dat de taak te laat was, maar ik had de laatste tijd met meerdere problemen te maken.','Ik werd overweldigd door verschillende projecten tegelijk.','Dank je dat je het begrijpt. Ik wist niet goed hoe ik het moest uitleggen.','Het nieuwe klantproject kostte veel meer tijd dan verwacht.','Ik weet niet zeker of ik je begrijp — kun je meer vertellen over wat je bedoelt?'),
   makeStage('Ik wilde het niet eerder bespreken omdat ik niet wist hoe je zou reageren.','Ik was bang dat het als een excuus zou klinken.','Dat betekent veel voor me, dank je. Het waren een paar moeilijke weken.','Ik moest een zieke collega ondersteunen naast mijn eigen werk.','Ik hoor je. Wat zou je helpen om dit beter te begrijpen?'),
   makeStage('Eerlijk gezegd besefte ik pas nu hoeveel dit het team beïnvloedde.','Ik onderschatte hoe strak de deadline eigenlijk was.','Ik waardeer het dat je niet meteen conclusies over mij trok.','Vanaf morgen kan ik jouw opleveringen als eerste prioriteren.','Kun je verduidelijken waarop je wilt dat ik me richt?'),
   makeStage('Ik wil dit oplossen. Hoe ziet een goed resultaat er voor jou uit?','Een duidelijk plan zou ons allebei helpen.','Ik heb het gevoel dat we dit nu echt samen kunnen oplossen.','Ik stuur je vandaag nog een aangepaste planning.','Laten we samen de volgende stap bepalen — wat stel je voor?')]},
  {id:'quality-gap',title:'Kwaliteitsverschil',situation:'Een bekwaam teamlid levert werk aan dat steeds opnieuw gecorrigeerd moet worden.',characterName:'Maya',characterRole:'Jouw teamlid',stages:[
   makeStage('Ik dacht dat het werk goed genoeg was, dus ik was verrast door de feedback.','Welk onderdeel van het werk veroorzaakte het grootste probleem?','Ik waardeer het dat je het uitlegt zonder het persoonlijk te maken.','De eisen veranderden twee keer terwijl ik eraan werkte.','Kun je een voorbeeld geven van wat je bedoelt?'),
   makeStage('Ik probeerde sneller te werken omdat het team onder druk staat.','Misschien heb ik de controle te snel gedaan.','Dat helpt om te horen. Ik was bang dat je geen vertrouwen meer in me had.','Ik kan een controlepunt toevoegen voordat ik de volgende versie indien.','Wat wil je dat ik als eerste verander?'),
   makeStage('Ik zie nu dat snelheid niet het enige doel was.','Wil je dat ik de eisen met je controleer voordat ik begin?','Dat maakt de verwachting veel duidelijker.','Ik stuur een korte checklist mee met de volgende versie.','Kunnen we afspreken wat “klaar” betekent vóór de volgende oplevering?'),
   makeStage('Ik denk dat ik nu weet wat ik anders moet doen.','Een specifieke kwaliteitschecklist zou me helpen dit consistent te herhalen.','Bedankt dat je me een weg vooruit geeft.','Ik gebruik de checklist bij de volgende drie opleveringen.','Wat is het belangrijkste dat je wilt dat ik onthoud?')]}]},
 conflict:{...en.conflict,id:'conflict-conversation-nl-v1',title:'Moeilijke conflicten · Voor managers',description:'Oefen om een gespannen gesprek te vertragen en conclusies te vervangen door vragen.',learningObjectives:['Herken je eerste interpretatie','Vraag voordat je intenties toeschrijft','Erken de impact','Spreek een volgende stap af'],scenarios:[{id:'meeting-friction',title:'Wrijving in vergaderingen',situation:'Een collega onderbreekt je herhaaldelijk tijdens vergaderingen en je begint dit te interpreteren als gebrek aan respect.',characterName:'Jordan',characterRole:'Jouw collega',stages:[
  makeStage('Ik besefte niet dat mijn onderbrekingen zo overkwamen.','Kun je vertellen welke momenten het meest storend waren?','Ik begrijp waarom dat frustrerend kan zijn.','Ik was bang dat we tijd tekort zouden komen en probeerde de discussie gaande te houden.','Ik denk dat we dezelfde vergadering misschien anders hebben ervaren.'),
  makeStage('Ik begrijp waarom je zou kunnen denken dat ik je afwees.','Was er een specifieke vergadering die dit extra moeilijk maakte?','Ik waardeer het dat je het rechtstreeks zegt.','Ik kan mijn punt opschrijven en de volgende keer wachten tot je klaar bent.','Wat zou de volgende vergadering anders maken voor jou?'),
  makeStage('Ik wil het patroon liever oplossen dan discussiëren over wie gelijk had.','Wat zou je merken als ik dit beter aanpak?','Dat lijkt me een eerlijke manier om het te benaderen.','Ik wacht met mijn opmerkingen tot je je punt hebt afgerond.','Welke verandering kunnen we samen proberen?'),
  makeStage('Dat klinkt praktisch. Daar kan ik mee werken.','Zullen we na de volgende vergadering even checken?','Bedankt dat je dit met me bespreekt.','Laten we vrijdag bekijken hoe het ging.','Ik denk dat we een werkbaar plan hebben.')]}]},
 leadership:{...en.leadership,id:'leadership-conversation-nl-v1',title:'Leiderschapsgesprekken · Voor managers',description:'Oefen om van antwoorden geven naar eigenaarschap creëren te bewegen met gerichte vragen.',learningObjectives:['Blijf nieuwsgierig onder druk','Nodig eigenaarschap uit','Maak verwachtingen duidelijk','Eindig met een gezamenlijke afspraak'],scenarios:[{id:'ownership-gap',title:'Gebrek aan eigenaarschap',situation:'Een direct report wacht steeds op jouw instructies in plaats van routinebeslissingen zelf te nemen.',characterName:'Sam',characterRole:'Jouw direct report',stages:[
  makeStage('Ik wacht meestal omdat ik geen verkeerde beslissing wil nemen.','Welke beslissingen voelen voor jou onduidelijk?','Dank je dat je dit uitlegt. Ik wil niet dat je het gevoel krijgt dat je moet falen.','Ik denk dat ik duidelijkere grenzen nodig heb voor wat ik zelf mag beslissen.','Ik probeer te begrijpen wat je van mij verwacht.'),
  makeStage('Ik besef dat ik misschien te vaak om goedkeuring heb gevraagd.','Welke beslissingen zou je mij toevertrouwen?','Het helpt te weten dat je wilt dat ik hierin groei.','Ik kan de wekelijkse prioriteiten zelfstandig bepalen zonder elk detail te controleren.','Kunnen we bepalen welke beslissingen ik zelf moet nemen?'),
  makeStage('Dat geeft me meer ruimte om te handelen.','Hoe ziet succes er na een maand uit?','Ik voel me zekerder nu de grens duidelijk is.','Ik breng uitzonderingen bij je in plaats van routinekeuzes voor te leggen.','Ik denk dat ik de nieuwe verwachting begrijp.'),
  makeStage('Ik kan dat oppakken.','Kunnen we de eerste paar beslissingen samen bekijken?','Bedankt dat je me ruimte geeft om te oefenen.','Ik neem de volgende beslissing zelfstandig en leg mijn redenering uit.','Ik ben er klaar voor.')]}]}
};

const defaults: Record<Language,Record<TrainingType,Curriculum>>={en,id,nl};

export const getCurriculum=(language:Language,type:TrainingType):Curriculum=>{
 const key=`mindmirror-curriculum:${language}:${type}`;
 try { const saved=localStorage.getItem(key); if(saved) return JSON.parse(saved) as Curriculum; } catch {}
 return defaults[language][type];
};
export const saveCurriculum=(language:Language,curriculum:Curriculum)=>localStorage.setItem(`mindmirror-curriculum:${language}:${curriculum.type}`,JSON.stringify(curriculum));
export const resetCurriculum=(language:Language,type:TrainingType)=>localStorage.removeItem(`mindmirror-curriculum:${language}:${type}`);
